"use client";
import { fetchOrdersReport } from "@/Redux/slices/Manager";
import { useDispatch, useSelector } from "react-redux";
import { useState } from "react";
import { RootState, AppDispatch } from "@/Redux/store/store";
import {
  FiInbox,
  FiDownload,
  FiSearch,
  FiCalendar,
  FiTrash2,
} from "react-icons/fi";
import jsPDF from "jspdf";
import { motion } from "framer-motion";

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1 },
  },
};

const itemVariants = {
  hidden: { y: 20, opacity: 0 },
  visible: { y: 0, opacity: 1 },
};

function formatDateLocal(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export default function OrdersReports() {
  const dispatch = useDispatch<AppDispatch>();
  const { ordersReport, loading, error } = useSelector(
    (state: RootState) => state.manager
  );

  // Default to last 24 hours
  const [from, setFrom] = useState<string>(() => {
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    return formatDateLocal(yesterday);
  });
  const [to, setTo] = useState<string>(() => formatDateLocal(new Date()));

  const orders = ordersReport?.orders ?? [];

  const totalOrders = orders.length;
  const totalPrice = orders.reduce(
    (sum, order) => sum + (order?.price ?? 0),
    0
  );
  const pendingOrders = orders.filter((o) => o.status === "pending").length;
  const completedOrders = orders.filter((o) => o.status === "completed").length;
  const cancelledOrders = orders.filter((o) => o.status === "cancelled").length;

  const handleSubmit = () => {
    // Trigger fetch by ensuring both dates are set (they always will be)
    if (from && to) {
      dispatch(fetchOrdersReport({ from, to }));
    }
  };

  const handleClear = () => {
    setFrom("");
    setTo("");
    dispatch(fetchOrdersReport({ from, to }));
  };

  const handleDownloadPDF = async () => {
    if (!ordersReport || orders.length === 0) return;

    const doc = new jsPDF();

    // Header background
    doc.setFillColor(249, 115, 22); // orange-500
    doc.rect(0, 0, 210, 40, "F");

    // Title
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.text("Orders Report", 105, 25, { align: "center" });

    // Date range subtitle
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.text(`From: ${from}  To: ${to}`, 105, 33, { align: "center" });

    // Summary cards background
    doc.setFillColor(255, 247, 237); // orange-50
    doc.rect(14, 50, 182, 30, "F");

    // Summary text
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.text(`Total Orders: ${totalOrders}`, 20, 60);
    doc.text(`Total Revenue: ₹${totalPrice.toFixed(2)}`, 20, 68);
    doc.text(`Pending: ${pendingOrders}`, 100, 60);
    doc.text(`Completed: ${completedOrders}`, 100, 68);
    doc.text(`Cancelled: ${cancelledOrders}`, 160, 60);

    // Table headers
    const headers = [
      "Food Name",
      "Price",
      "Table No.",
      "Created At",
      "Order Status",
      "Waiter",
    ];
    const data = orders.map((order) => [
      order.food?.foodName ?? "—",
      order?.price ? `₹${order.price}` : "—",
      order?.tableNo ?? "—",
      new Date(order.createdAt).toLocaleString(),
      order?.status ?? "—",
      order?.weater?.name ?? "—",
    ]);

    // Dynamically import and apply the plugin
    const autoTable = (await import("jspdf-autotable")).default;
    autoTable(doc, {
      head: [headers],
      body: data,
      startY: 90,
      theme: "grid",
      headStyles: {
        fillColor: [249, 115, 22], // orange-500
        textColor: 255,
        fontStyle: "bold",
        halign: "center",
      },
      bodyStyles: { halign: "center" },
      alternateRowStyles: { fillColor: [255, 247, 237] }, // orange-50
      margin: { left: 14, right: 14 },
      tableWidth: 182,
    });

    // Footer
    const finalY =
      (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable
        .finalY + 10;
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by Hotel Management System", 105, finalY, {
      align: "center",
    });

    doc.save(`Orders_Report_${from}_to_${to}.pdf`);
  };

  return (
    <div className="min-h-screen bg-[#f8fafc]">
      <section className="max-w-7xl mx-auto px-4 sm:px-6 py-8 md:py-12">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
          <motion.div
            variants={itemVariants}
            initial="hidden"
            animate="visible"
          >
            <h1 className="text-4xl font-black text-gray-900">
              Orders <span className="text-orange-500">Report</span>
            </h1>
            <p className="text-gray-500 mt-1 font-medium">
              Analyze your restaurants sales performance
            </p>
          </motion.div>

          <motion.div
            variants={itemVariants}
            initial="hidden"
            animate="visible"
            className="flex flex-wrap gap-3"
          >
            <button
              onClick={handleDownloadPDF}
              disabled={!ordersReport || orders.length === 0}
              className="flex items-center gap-2 px-6 py-3 rounded-2xl bg-white border border-gray-100 text-gray-700 font-bold shadow-sm hover:shadow-md transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <FiDownload className="text-orange-500" />
              Download PDF
            </button>
          </motion.div>
        </div>

        {/* Filters */}
        <motion.div
          variants={itemVariants}
          initial="hidden"
          animate="visible"
          className="bg-white p-6 sm:p-8 rounded-[2.5rem] shadow-sm border border-gray-100 mb-12"
        >
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 items-end">
            <div>
              <label className="block text-sm font-bold text-gray-400 uppercase tracking-widest mb-3 ml-1">
                From Date
              </label>
              <div className="relative">
                <FiCalendar className="absolute left-5 top-1/2 -translate-y-1/2 text-gray-400" />
                <input
                  type="date"
                  value={from}
                  onChange={(e) => setFrom(e.target.value)}
                  className="w-full pl-12 pr-6 py-4 bg-gray-50 border-2 border-transparent focus:border-orange-500 focus:bg-white rounded-2xl outline-none transition-all text-gray-800 font-bold"
                />
              </div>
            </div>
            <div>
              <label className="block text-sm font-bold text-gray-400 uppercase tracking-widest mb-3 ml-1">
                To Date
              </label>
              <div className="relative">
                <FiCalendar className="absolute left-5 top-1/2 -translate-y-1/2 text-gray-400" />
                <input
                  type="date"
                  value={to}
                  onChange={(e) => setTo(e.target.value)}
                  className="w-full pl-12 pr-6 py-4 bg-gray-50 border-2 border-transparent focus:border-orange-500 focus:bg-white rounded-2xl outline-none transition-all text-gray-800 font-bold"
                />
              </div>
            </div>
            <div className="flex gap-3">
              <button
                onClick={handleSubmit}
                className="flex-1 flex items-center justify-center gap-2 bg-orange-500 text-white py-4 rounded-2xl font-black shadow-xl shadow-orange-200 hover:bg-orange-600 transition-all"
              >
                <FiSearch />
                Generate
              </button>
              <button
                onClick={handleClear}
                className="px-6 bg-gray-100 text-gray-500 py-4 rounded-2xl font-bold hover:bg-gray-200 transition-all"
              >
                Clear
              </button>
            </div>
          </div>
        </motion.div>

        {error && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-md mx-auto bg-white rounded-3xl shadow-2xl p-8 border border-red-50 text-center mb-12"
          >
            <div className="w-20 h-20 bg-red-50 rounded-full flex items-center justify-center mx-auto mb-6">
              <FiTrash2 className="text-red-500 text-3xl" />
            </div>
            <h2 className="text-2xl font-bold text-gray-800 mb-2">Error</h2>
            <p className="text-gray-600 mb-8">
              {typeof error === "string"
                ? error
                : (error as { message?: string })?.message ||
                  "Failed to load report"}
            </p>
            <button
              onClick={handleSubmit}
              className="w-full bg-orange-500 text-white py-4 rounded-2xl font-bold hover:bg-orange-600 transition-all shadow-lg shadow-orange-200"
            >
              Try Again
            </button>
          </motion.div>
        )}

        {loading && (
          <div className="flex flex-col items-center justify-center py-20">
            <motion.div
              animate={{ rotate: 360 }}
              transition={{ repeat: Infinity, duration: 1, ease: "linear" }}
              className="w-12 h-12 border-4 border-orange-500 border-t-transparent rounded-full mb-4"
            />
            <p className="text-gray-600 font-medium">Fetching Report Data...</p>
          </div>
        )}

        {!loading && !error && (!ordersReport || orders.length === 0) && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="flex flex-col items-center justify-center py-20 bg-white rounded-[2.5rem] border-2 border-dashed border-gray-100"
          >
            <div className="w-20 h-20 bg-orange-50 rounded-full flex items-center justify-center mb-4">
              <FiInbox className="text-orange-200 text-4xl" />
            </div>
            <h3 className="text-xl font-bold text-gray-800">
              No data to display
            </h3>
            <p className="text-gray-500 mt-2 font-medium">
              Select a date range to generate a report
            </p>
          </motion.div>
        )}

        {!loading && !error && ordersReport && orders.length > 0 && (
          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="space-y-8"
          >
            {/* Summary Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {[
                {
                  label: "Total Orders",
                  value: totalOrders,
                  color: "text-orange-500",
                  bg: "bg-orange-50",
                },
                {
                  label: "Total Revenue",
                  value: `₹${totalPrice.toFixed(2)}`,
                  color: "text-green-500",
                  bg: "bg-green-50",
                },
                {
                  label: "Completed",
                  value: completedOrders,
                  color: "text-blue-500",
                  bg: "bg-blue-50",
                },
                {
                  label: "Pending",
                  value: pendingOrders,
                  color: "text-yellow-500",
                  bg: "bg-yellow-50",
                },
              ].map((stat, i) => (
                <motion.div
                  key={i}
                  variants={itemVariants}
                  className="bg-white p-8 rounded-[2rem] border border-gray-100 shadow-sm"
                >
                  <p className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-2">
                    {stat.label}
                  </p>
                  <p className={`text-3xl font-black ${stat.color}`}>
                    {stat.value}
                  </p>
                </motion.div>
              ))}
            </div>

            {/* Table */}
            <motion.div
              variants={itemVariants}
              className="bg-white rounded-[2.5rem] shadow-sm border border-gray-100 overflow-hidden"
            >
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-gray-50/50">
                      {[
                        "Food Name",
                        "Price",
                        "Table No.",
                        "Created At",
                        "Status",
                        "Waiter",
                      ].map((header) => (
                        <th
                          key={header}
                          className="px-8 py-6 text-sm font-bold text-gray-400 uppercase tracking-widest border-b border-gray-100"
                        >
                          {header}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-50">
                    {orders.map((order) => (
                      <tr
                        key={order._id}
                        className="group hover:bg-gray-50/50 transition-colors"
                      >
                        <td className="px-8 py-6">
                          <p className="font-bold text-gray-800">
                            {order.food?.foodName ?? "—"}
                          </p>
                        </td>
                        <td className="px-8 py-6">
                          <p className="font-black text-green-600">
                            ₹{order?.price ?? "—"}
                          </p>
                        </td>
                        <td className="px-8 py-6 text-center">
                          <span className="px-4 py-2 bg-purple-50 text-purple-600 rounded-xl font-bold text-sm">
                            {order?.tableNo ?? "—"}
                          </span>
                        </td>
                        <td className="px-8 py-6 whitespace-nowrap">
                          <p className="text-gray-500 font-medium text-sm">
                            {new Date(order.createdAt).toLocaleDateString()}
                            <span className="block text-xs text-gray-400">
                              {new Date(order.createdAt).toLocaleTimeString()}
                            </span>
                          </p>
                        </td>
                        <td className="px-8 py-6">
                          <span
                            className={`px-4 py-2 rounded-xl text-xs font-black uppercase tracking-wider ${
                              order?.status === "completed"
                                ? "bg-green-50 text-green-600"
                                : order?.status === "pending"
                                ? "bg-yellow-50 text-yellow-600"
                                : "bg-red-50 text-red-600"
                            }`}
                          >
                            {order?.status ?? "—"}
                          </span>
                        </td>
                        <td className="px-8 py-6">
                          <p className="font-bold text-gray-700">
                            {order?.weater?.name ?? "—"}
                          </p>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </motion.div>
          </motion.div>
        )}
      </section>
    </div>
  );
}
