"use client";
import { fetchOrdersReport } from "@/Redux/slices/Manager";
import { useDispatch, useSelector } from "react-redux";
import { useState } from "react";
import { RootState, AppDispatch } from "@/Redux/store/store";
import { FiInbox } from "react-icons/fi";
import jsPDF from "jspdf";
// jspdf-autotable is imported dynamically in handleDownloadPDF to avoid build-time resolution issues

function formatDateLocal(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export default function OrdersReports() {
  const dispatch = useDispatch<AppDispatch>();
  const { ordersReport, loading, error } = useSelector(
    (state: RootState) => state.manager
  );

  // Default to last 24 hours
  const [from, setFrom] = useState<string>(() => {
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    return formatDateLocal(yesterday);
  });
  const [to, setTo] = useState<string>(() => formatDateLocal(new Date()));

  // Frontend calculations
  const totalOrders = ordersReport?.orders.length ?? 0;
  const totalPrice =
    ordersReport?.orders.reduce((sum, order) => sum + (order.price ?? 0), 0) ??
    0;
  const pendingOrders =
    ordersReport?.orders.filter((o) => o.status === "pending").length ?? 0;
  const completedOrders =
    ordersReport?.orders.filter((o) => o.status === "completed").length ?? 0;
  const cancelledOrders =
    ordersReport?.orders.filter((o) => o.status === "cancelled").length ?? 0;

  const handleSubmit = () => {
    // Trigger fetch by ensuring both dates are set (they always will be)
    if (from && to) {
      dispatch(fetchOrdersReport({ from, to }));
    }
  };

  const handleClear = () => {
    setFrom("");
    setTo("");
    dispatch(fetchOrdersReport({ from, to }));
  };

  const handleDownloadPDF = async () => {
    if (!ordersReport || ordersReport.orders.length === 0) return;

    const doc = new jsPDF();

    // Header background
    doc.setFillColor(249, 115, 22); // orange-500
    doc.rect(0, 0, 210, 40, "F");

    // Title
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.text("Orders Report", 105, 25, { align: "center" });

    // Date range subtitle
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.text(`From: ${from}  To: ${to}`, 105, 33, { align: "center" });

    // Summary cards background
    doc.setFillColor(255, 247, 237); // orange-50
    doc.rect(14, 50, 182, 30, "F");

    // Summary text
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.text(`Total Orders: ${totalOrders}`, 20, 60);
    doc.text(`Total Revenue: ₹${totalPrice.toFixed(2)}`, 20, 68);
    doc.text(`Pending: ${pendingOrders}`, 100, 60);
    doc.text(`Completed: ${completedOrders}`, 100, 68);
    doc.text(`Cancelled: ${cancelledOrders}`, 160, 60);

    // Table headers
    const headers = [
      "Food Name",
      "Price",
      "Table No.",
      "Created At",
      "Order Status",
      "Waiter",
    ];
    const data = ordersReport.orders.map((order) => [
      order.foodId?.foodName ?? "—",
      order?.price ? `₹${order.price}` : "—",
      order?.tableNo ?? "—",
      new Date(order.createdAt).toLocaleString(),
      order?.status ?? "—",
      order?.weaterId?.name ?? "—",
    ]);

    // Dynamically import and apply the plugin
    const autoTable = (await import("jspdf-autotable")).default;
    autoTable(doc, {
      head: [headers],
      body: data,
      startY: 90,
      theme: "grid",
      headStyles: {
        fillColor: [249, 115, 22], // orange-500
        textColor: 255,
        fontStyle: "bold",
        halign: "center",
      },
      bodyStyles: { halign: "center" },
      alternateRowStyles: { fillColor: [255, 247, 237] }, // orange-50
      margin: { left: 14, right: 14 },
      tableWidth: 182,
    });

    // Footer
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by Hotel Management System", 105, finalY, {
      align: "center",
    });

    doc.save(`Orders_Report_${from}_to_${to}.pdf`);
  };

  return (
    <section
      className="min-h-screen px-6 py-10"
      style={{ backgroundColor: "#ffffff" }}
    >
      <div className="max-w-6xl mx-auto">
        <h2 className="text-3xl font-bold mb-8 text-orange-600">
          Orders Report
        </h2>

        <div className="flex flex-col md:flex-row gap-4 mb-8">
          <div className="flex-1">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              From
            </label>
            <input
              type="date"
              value={from}
              onChange={(e) => setFrom(e.target.value)}
              className="w-full border border-gray-300 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-orange-500 text-gray-800 bg-white shadow-sm transition"
            />
          </div>
          <div className="flex-1">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              To
            </label>
            <input
              type="date"
              value={to}
              onChange={(e) => setTo(e.target.value)}
              className="w-full border border-gray-300 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-orange-500 text-gray-800 bg-white shadow-sm transition"
            />
          </div>
          <div className="flex items-end gap-2">
            <button
              onClick={handleSubmit}
              className="px-4 py-3 rounded-xl bg-orange-500 text-white hover:bg-orange-600 transition"
            >
              Submit
            </button>
            <button
              onClick={handleClear}
              className="px-4 py-3 rounded-xl bg-gray-200 text-gray-700 hover:bg-gray-300 transition"
            >
              Clear
            </button>
            <button
              onClick={handleDownloadPDF}
              disabled={!ordersReport || ordersReport.orders.length === 0}
              className={`px-4 py-3 rounded-xl text-white transition ${
                !ordersReport || ordersReport.orders.length === 0
                  ? "bg-gray-400 cursor-not-allowed"
                  : "bg-orange-500 hover:bg-orange-600"
              }`}
            >
              Download PDF
            </button>
          </div>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-xl shadow-lg p-6 max-w-md mx-auto text-center mb-8">
            <div className="text-red-500 mb-3">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-12 w-12 mx-auto"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            </div>
            <h3 className="text-lg font-semibold text-red-700 mb-2">
              Something went wrong
            </h3>
            <p className="text-red-600">
              {typeof error === "string"
                ? error
                : (error as { message?: string })?.message || "Unknown error"}
            </p>
          </div>
        )}

        {loading && (
          <div className="flex items-center justify-center py-20">
            <div className="text-center">
              <div className="w-12 h-12 border-4 border-orange-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
              <p className="text-gray-700">Loading orders...</p>
            </div>
          </div>
        )}

        {!loading && !error && !ordersReport && (
          <div className="flex items-center justify-center py-20">
            <div className="text-center">
              <FiInbox className="h-20 w-20 mx-auto text-orange-400 mb-4" />
              <h3 className="text-xl font-semibold text-orange-600">
                No data fetched yet
              </h3>
              <p className="text-gray-600 mt-2">
                Please select a date range to view orders.
              </p>
            </div>
          </div>
        )}

        {!loading &&
          !error &&
          ordersReport &&
          ordersReport.orders.length === 0 && (
            <div className="flex items-center justify-center py-20">
              <div className="text-center">
                <FiInbox className="h-20 w-20 mx-auto text-orange-400 mb-4" />
                <h3 className="text-xl font-semibold text-orange-400">
                  No orders found
                </h3>
                <p className="text-gray-600 mt-2">
                  No orders found for the selected period.
                </p>
              </div>
            </div>
          )}

        {!loading &&
          !error &&
          ordersReport &&
          ordersReport.orders.length > 0 && (
            <>
              <div className="overflow-x-auto rounded-xl shadow-lg border border-gray-200">
                <table className="min-w-full border-collapse bg-white">
                  <thead>
                    <tr className="bg-orange-500 text-white">
                      <th className="px-6 py-4 text-left font-semibold">
                        Food Name
                      </th>
                      <th className="px-6 py-4 text-left font-semibold">
                        Price
                      </th>
                      <th className="px-6 py-4 text-left font-semibold">
                        Table No.
                      </th>
                      <th className="px-6 py-4 text-left font-semibold">
                        Created At
                      </th>
                      <th className="px-6 py-4 text-left font-semibold">
                        Order Status
                      </th>
                      <th className="px-6 py-4 text-left font-semibold">
                        Waiter
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {ordersReport.orders.map((order) => {
                      return (
                        <tr
                          key={order._id}
                          className="hover:bg-orange-50 transition-colors"
                        >
                          <td className="px-6 py-4 text-blue-700 font-medium">
                            {order.foodId?.foodName ?? "—"}
                          </td>
                          <td className="px-6 py-4 text-green-600 font-semibold">
                            {order?.price ? `₹${order.price}` : "—"}
                          </td>
                          <td className="px-6 py-4 text-purple-600 text-center font-medium">
                            {order?.tableNo ?? "—"}
                          </td>
                          <td className="px-6 py-4 text-indigo-700 whitespace-nowrap font-medium">
                            {new Date(order.createdAt).toLocaleString()}
                          </td>
                          <td
                            className={`px-6 py-4 capitalize font-semibold ${
                              order?.status === "pending"
                                ? "text-yellow-600"
                                : order?.status === "completed"
                                ? "text-green-600"
                                : order?.status === "cancelled"
                                ? "text-red-600"
                                : "text-gray-800"
                            }`}
                          >
                            {order?.status ?? "—"}
                          </td>
                          <td className="px-6 py-4 text-teal-700 font-medium">
                            {order?.weaterId?.name ?? "—"}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>

              {/* Summary Section */}
              <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                <div className="bg-white rounded-xl shadow-md border border-gray-200 p-6 text-center">
                  <h3 className="text-lg font-semibold text-gray-700 mb-2">
                    Total Orders
                  </h3>
                  <p className="text-3xl font-bold text-orange-600">
                    {totalOrders}
                  </p>
                </div>
                <div className="bg-white rounded-xl shadow-md border border-gray-200 p-6 text-center">
                  <h3 className="text-lg font-semibold text-gray-700 mb-2">
                    Total Revenue
                  </h3>
                  <p className="text-3xl font-bold text-green-600">
                    ₹{totalPrice.toFixed(2)}
                  </p>
                </div>
                <div className="bg-white rounded-xl shadow-md border border-gray-200 p-6 text-center">
                  <h3 className="text-lg font-semibold text-gray-700 mb-2">
                    Pending
                  </h3>
                  <p className="text-3xl font-bold text-yellow-600">
                    {pendingOrders}
                  </p>
                </div>
                <div className="bg-white rounded-xl shadow-md border border-gray-200 p-6 text-center">
                  <h3 className="text-lg font-semibold text-gray-700 mb-2">
                    Completed
                  </h3>
                  <p className="text-3xl font-bold text-green-600">
                    {completedOrders}
                  </p>
                </div>
              </div>
            </>
          )}
      </div>
    </section>
  );
}
